### ---------------- Tasks ----------------

### Testing get all tasks.
GET http://localhost:5000/api/tasks

### Testing get a single task
GET http://localhost:5000/api/tasks/<task_id>

### Testing get user tasks
GET http://localhost:5000/api/tasks/user/<user_id>

### Testing create a task
POST http://localhost:5000/api/tasks
Content-type: application/json

{
    "title": "This is a test task",
    "description": "This is a task description",
    "priority": "HIGH",
    "status": "BACKLOG",
    "assignedUsersId": [1, 2, 3]   
}

### Testing update a task
PUT http://localhost:5000/api/tasks/<task_id>
Content-type: application/json

{
    "title": "New task title",
    "description": "New task description",
    "priority": "MEDIUM",
    "status": "BACKLOG",
    "assignedUsersId": [1, 2, 3, 4, 5]   
}

### Delete a task
DELETE http://localhost:5000/api/tasks/<task_id>

